language: objective-c

cache:
  bundler: true
  cocoapods: true
podfile: Podfile

jobs:
  include:
    - osx_image: xcode10.2
      env: 'XCODE_DESTINATION="platform=iOS Simulator,OS=9.0,name=iPhone 6"'
    - osx_image: xcode11.2
      env: 'XCODE_DESTINATION="platform=iOS Simulator,OS=13.2,name=iPhone X"'

before_install:
  - gem install cocoapods --no-document --quiet
  - pod --version
  - pod repo update
  - brew update
  - brew install xcodegen
  - xcodegen --version

script:
  - xcodebuild -workspace NIM.xcworkspace -scheme NIM -destination "${XCODE_DESTINATION}" | xcpretty
  - Scripts/update-source.sh
  - xcodebuild -workspace NIM.xcworkspace -scheme NIM -destination "${XCODE_DESTINATION}" | xcpretty
