name: NIM

options:
  createIntermediateGroups: true
  usesTabs: false
  indentWidth: 4
  tabWidth: 4
  deploymentTarget:
    iOS: '10.0'

attributes:
  CLASSPREFIX: NTES
  ORGANIZATIONNAME: Netease

targets:
  NIM:
    type: application
    platform: iOS
    sources:
      - path: NIMDemo
        excludes:
          - "**/*.{framework,a}"
          - "Supporting Files/Files"
          - "Supporting Files/*.{xcconfig,sh}"
          - "Classes/**/*Robot*.{h,m,xib}"
          - "Classes/**/NTESContactViewController.xib"
      - path: NIMDemo/Supporting Files/Files
        type: folder
    settings:
      base:
        MARKETING_VERSION: 1.0.0
        PRODUCT_BUNDLE_IDENTIFIER: com.netease.NIM.demo
        INFOPLIST_FILE: NIMDemo/Supporting Files/English.lproj/Info.plist
        GCC_PREFIX_HEADER: NIMDemo/NIMDemo-Prefix.pch
        ASSETCATALOG_COMPILER_LAUNCHIMAGE_NAME: LaunchImage
        # Fix warning for Xcode 11.3: Enable "Missing Localizability"
        CLANG_ANALYZER_LOCALIZABILITY_NONLOCALIZED: YES
      configs:
        Debug:
          XCCONFIG_BUNDLE_NAME: 网易云信开发版
          CODE_SIGN_ENTITLEMENTS: NIMDemo/Supporting Files/NIMDev.entitlements
        Release:
          XCCONFIG_BUNDLE_NAME: 云信 Demo
          CODE_SIGN_ENTITLEMENTS: NIMDemo/Supporting Files/NIMPro.entitlements
    dependencies:
      - framework: NIMDemo/Classes/Vendors/AlipaySDK/AlipaySDK.framework
        embed: false
      - framework: NIMDemo/Classes/Vendors/RedPacket/JrmfPacketKit.framework
        embed: false
      - framework: NIMDemo/Classes/Vendors/RedPacket/JrmfWalletKit.framework
        embed: false
      - framework: NIMDemo/Classes/Vendors/RedPacket/JYangToolKit.framework
        embed: false
      - sdk: CFNetwork.framework
      - sdk: CoreMotion.framework
      - sdk: CoreText.framework
      - sdk: Security.framework
      - sdk: CallKit.framework
        weak: true
      - sdk: UserNotifications.framework
        weak: true
      - sdk: UserNotificationsUI.framework
        weak: true
    postBuildScripts:
      - script: '"${PODS_ROOT}/Fabric/run" d395159c291c627c9d4ff9139bf8f0a700b98732 67e6161c740f31f9fbe224ccde008e034af47dfdaa04c97cc8f46111d523cb76'
        name: Run Fabric
        runOnlyWhenInstalling: true
